@startuml

scale 1.5
class ManageTestCases {
    + config:設定ファイル
    + contest:コンテスト名
    + RegisterUser():ユーザー情報等を設定する
    + GetTestCases():テストケースを取得する
    + AddTestCases():テストケースを追加する
    - __UpdateConf():設定ファイル読込
    - __ReadFile():テストケース読込
    - __WriteFile():テストケース書込
    - __LoginPage():ログイン処理
    - __ScrapePage():webページ取得
    - __AnalyzePage():webページ解析
}

class ExecuteTestCases {
    + testinfo:テスト対象の情報
    + testCases:テストケース
    + result:テスト結果
    + Execute():テストを実行する
    - __GetPath():ソースコードのpath生成
    - __Build():ビルド
    - __Run():実行
    - __Result():結果出力
}

@enduml